### ISSUE TITLE
Where to type the text and select the language?

### ISSUE THREAD

**Issue by Tobe2d** [Foxify52/RVG_tts#2]
I manages to install it and run `python RVG.py` and I got the output file `output.wav`

but I cant find out where to write me text and select the language.

Could you point it out please.

**Comment by Foxify52** [comment]
Go ahead and run ```python rvg.py -h``` and it'll list out all of the available commands and their descriptions. The one you want is ```--input_text ""```. Different languages aren't supported as of now.

**Comment by Tobe2d** [comment]
Thanks @Foxify52 for the reply.

So as of now it work only for english?

Any plans for other languages?

**Comment by Foxify52** [comment]
I haven't decided yet. Code side, additional languages can be added without too much complication. model side is a different story. I don't really have a dataset like ljspeech in other languages nor do I have the hardware to train it to 90k steps like it needs to be. if someone would help out with that, I'd be willing to add in other languages for sure.

**Comment by Tobe2d** [comment]
I can help on the training if you need it ;-)
You just have to send me the steps and datasets and consider it done ;-)

**Comment by Foxify52** [comment]
Alright well if I'm able to find a dataset or someone else can provide a dataset for a specific language, I'll reopen this as a feature request and mention you there.

**Comment by Tobe2d** [comment]
How can I reach out to you?
I want to discuss potental proejct ;-)
